<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bricks\Model\DefaultModel'                => __DIR__ . '/src/Bricks/Model/DefaultModel.php',
    'Bricks\Model\Model'                       => __DIR__ . '/src/Bricks/Model/Model.php',
    'Bricks\Model\ModelInterface'              => __DIR__ . '/src/Bricks/Model/ModelInterface.php',
    'Bricks\Model\ServiceManager\ModelFactory' => __DIR__ . '/src/Bricks/Model/ServiceManager/ModelFactory.php',
);
